### ISSUE TITLE
Missing version tags for images

### ISSUE THREAD

**Issue by ac-miller** [knative/infra#456]
## Expected Behavior
Related to https://github.com/knative/eventing/issues/5574
When pulling this image, it is expected to see semver tags (or some other versioning)
gcr.io/knative-releases/knative.dev/pkg/apiextensions/storageversion/cmd/migrate

## Actual Behavior
There are no versions, only "latest"

## Steps to Reproduce the Problem

1. Attempt to pull an image

**Comment by dprotaso** [comment]
Moving this to test/infra cause I'm not sure what's the best thing to do here. We could just start tagging the image.

**Comment by dprotaso** [comment]
Alternatively we could refactor the logic out of the main method here into a function and call those in respective repos (serving, eventing)

https://github.com/knative/pkg/blob/main/apiextensions/storageversion/cmd/migrate/main.go

**Comment by asr2003** [comment]
@dprotaso For Approach1 that images are uniquely tagged to prevent overwriting. Can we have a reusable action something like this?

```
on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Docker image name'
        required: true
        type: string
      repo-name:
        description: 'Repository name'
        required: true
        type: string
```

And we can update the serving/eventing workflow like this:

```
name: Build and Release

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  build-and-release:
    uses: knative/actions/.github/workflows/reusable-go-build.yaml@main
    with:
      docker-image-name: "knative.dev/pkg/apiextensions/storageversion/cmd/migrate"
      repo-name: "serving/eventing"

```
