### ISSUE TITLE
Python virtual env to use in GH actions

### ISSUE THREAD

**Issue by dsimansk** [knative/infra#530]
Let's open an issue to properly investigate this for all python deps? Options are:
- use `break-system-packages` flag as a workaround
- use virtual env
- use system package manager or pipx

_Originally posted by @skonto in https://github.com/knative/community/pull/1620#discussion_r1795357143_

The issues popped up in knative/community Peribolos check, but we have a couple more of places that uses Python tools. That can have the same symptoms. 

Related to GH runner update of python package: https://github.com/actions/runner-images/issues/8615

**Comment by dsimansk** [comment]
Some of the options:

Use `--break-system-packages`
```
pip install strictyaml --break-system-packages
```

Pin Python version to previous one:
```
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"    
    - run: pip install strictyaml
```

Init the full virtual env?

/cc @knative/productivity-leads
